# Generated by Django 2.2.5 on 2019-10-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_DB',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('noun', models.CharField(max_length=20)),
                ('skill', models.CharField(max_length=20)),
                ('item_room', models.CharField(max_length=20, null=True)),
                ('item_owner', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room_DB',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('coords', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('n_to', models.CharField(max_length=20, null=True)),
                ('s_to', models.CharField(max_length=20, null=True)),
                ('e_to', models.CharField(max_length=20, null=True)),
                ('w_to', models.CharField(max_length=20, null=True)),
                ('u_to', models.CharField(max_length=20, null=True)),
                ('d_to', models.CharField(max_length=20, null=True)),
                ('region', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('roomitemsids', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
