# Generated by Django 2.2.5 on 2019-10-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20191022_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_db',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
