# Generated by Django 2.2.5 on 2019-10-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_db',
            name='playerNames',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
