# Generated by Django 2.2.5 on 2019-10-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_auto_20191022_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalnote',
            name='note_ptr',
        ),
        migrations.RemoveField(
            model_name='personalnote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='PersonalNote',
        ),
    ]
