# Generated by Django 2.2.5 on 2019-10-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_room_db_playernames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_db',
            name='playerNames',
        ),
        migrations.AlterField(
            model_name='player',
            name='currentRoom',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
