# Generated by Django 2.2.5 on 2019-10-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_auto_20191024_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='inv',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='room_db',
            name='itemdesc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
